# Generated by Django 5.1.4 on 2025-01-28 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_author'),
        ('blog', '0002_blog_tags'),
    ]

    operations = [
    ]
