# Generated by Django 5.1.4 on 2025-03-26 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("post", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="post",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        )
    ]
