# Generated by Django 5.1.4 on 2025-04-01 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("post", "0002_post_published_at")]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="published_at",
            field=models.DateField(blank=True, null=True),
        )
    ]
