# Generated by Django 5.1.5 on 2025-02-20 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news_letter', '0005_alter_newsletter_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('status', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('news_letter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='news_letter.newsletter')),
            ],
            options={
                'db_table': 'subscribers',
            },
        ),
    ]
