# Generated by Django 4.2.18 on 2025-01-31 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("user", "0002_alter_profile_image")]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="description",
            field=models.TextField(blank=True, null=True),
        )
    ]
