# Generated by Django 5.1.5 on 2025-02-19 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_letter', '0003_alter_newsletter_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='content',
            field=models.TextField(),
        ),
    ]
