# Generated by Django 5.1.5 on 2025-02-20 05:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_letter', '0004_alter_newsletter_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
