# Generated by Django 5.1.5 on 2025-02-25 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_letter', '0005_alter_newsletter_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='author',
        ),
    ]
