# Generated by Django 5.1.5 on 2025-02-25 04:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_letter', '0006_remove_newsletter_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='group',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_letters', to=settings.AUTH_USER_MODEL),
        ),
    ]
